confluentinc/common

utils/pom.xml
The client currently is set to 0.3, which is based on zookeeper 3.3.1. I propose we upgrade it.
=> Upgrade zk client.

config/src/main/java/io/confluent/common/config/AbstractConfig.java
=> Fix logging of unsued options always showing null.

config/pom.xml, metrics/pom.xml, package/pom.xml, pom.xml, utils/pom.xml
=> Bump version to 2.0.1

package/src/assembly/package.xml, version.txt
Common/master updates for CP-140.  @ewencp if it looks good to you, I'll push the same changes on 3.0.x after this one gets merged in.
=> CP-140: commons changes

config/src/main/java/io/confluent/common/config/AbstractConfig.java
=> add originalsWithPrefix just like kafka

config/src/main/java/io/confluent/common/config/AbstractConfig.java
=> turns out if you want to override values, you need values. not originals

pom.xml
This is the version that Kafka 0.10.1.0 uses.
=> Update zkclient to 0.9

metrics/src/main/java/io/confluent/common/metrics/stats/Min.java
=> min needs to start at max_value. hard to get lower than min

config/src/main/java/io/confluent/common/config/ConfigUtils.java, config/src/test/java/io/confluent/common/config/ConfigUtilsTest.java, utils/src/main/java/io/confluent/common/utils/Utils.java
See https://confluentinc.atlassian.net/browse/CPKAFKA-437
=> CPKAFKA-437: add ConfigUtils#translateDeprecated and ConfigUtilsTest

config/src/main/java/io/confluent/common/config/ConfigUtils.java, config/src/test/java/io/confluent/common/config/ConfigUtilsTest.java
without this we will filter everything in a synonym group if all we get is something in synonym[0]
=> CP-411 we need to allow keys that match synonym[0] through

config/pom.xml, metrics/pom.xml, package/pom.xml, pom.xml, utils/pom.xml
=> ST-240 Coverage+findbugs

config/pom.xml, metrics/pom.xml, package/pom.xml, pom.xml
this covers at least rest-utils/schema-registry/REDACTED
=> moving even more deps from downstream to common

config/src/main/java/io/confluent/common/config/ConfigDef.java, config/src/test/java/io/confluent/common/config/ConfigDefTest.java
Fixes a bunch of system tests failures. 
Signed-off-by: Arjun Satish <arjun@confluent.io>
=> CC-1444: Use current thread's classloader if available

pom.xml
We did the same for Kafka recently.
=> Bump zookeeper to 3.4.12

pom.xml
see https://github.com/spotify/dockerfile-maven/issues/90#issuecomment-345508749
=> support running docker maven plugin with jdk 10

pom.xml
- Introduce java.version variable.
- Remove MaxPermSize.
=> ST-304: Update source/target/release to 8

pom.xml
This includes a fix for ZOOKEEPER-2184 (Zookeeper Client
should re-resolve hosts when connection attempts fail).
Apache Kafka PR: https://github.com/apache/kafka/pull/5376
=> Update ZooKeeper to 3.4.13

pom.xml
Related public PRs:
* https://github.com/apache/kafka/pull/5530
* https://github.com/confluentinc/ksql/pull/2074
* https://github.com/confluentinc/support-metrics-client/pull/54
Tested with muckrake that all projects compile fine if all the PRs are merged.
=> Use Scala 2.12

config/src/main/java/io/confluent/common/config/AbstractConfig.java, config/src/main/java/io/confluent/common/config/ConfigDef.java, config/src/main/java/io/confluent/common/config/ConfigException.java, config/src/main/java/io/confluent/common/config/ConfigUtils.java, config/src/main/java/io/confluent/common/config/types/Password.java
Reverts confluentinc/common#178
this had some deleterious effects on downstream repos. will address those before reopening
=> Revert "deprecate common configs"

package/src/assembly/package.xml
Plan to use pint to apply changes to all dev branches.
=> 3.3.x:use maven to generate archives

pom.xml
=> DG-42: Upgrade to Avro 1.9.1

build-tools/src/main/resources/checkstyle/checkstyle.xml
Allow downstream projects to optional enable the `todoComment` check.
=> todoComment check

pom.xml
Fixes some false-positives reported on downstream dependencies
=> update depencency check to the latest version

pom.xml
Upgrade Avro to 1.9.2, Jackson to 2.10.2
=> Upgrade Avro to 1.9.2

pom.xml
This aligns this repo with kafka.
=> Update ZooKeeper to 3.5.7

pom.xml
Upgrade jackson and jackson-bom to the most recent versions to resolve known CVEs
Upgrade Avro to 1.9.2 in 5.4.x
=> Upgrade Jackson to 2.10.2 and Avro to 1.9.2

Makefile
The archive branch make file was not applying patches like the debian and rpm branches do. This is probably because up until now there weren't any patches. Now that we use nano versioning we resolve the kafka versions and create a patch to the pom file. This was being done in those other branches and the builds work when doing that, but the archive build was failing because of this. This is just copy and pasted from those other branches.
I am testing this change with this packaging PR job. That packaging job will fail because of other outstanding issues but we will be able to see that the patches were applied and the make file works.
https://github.com/confluentinc/packaging/pull/823
=> ST-3461: The archive branch was not applying patches like the debian and rpm branches

pom.xml
See https://github.com/apache/kafka/commit/7f90a58b69cd0eb63ba122b41e6ef6195b0a5d98
=> Upgrade scala to 2.13.3 to align with Kafka

pom.xml
https://mvnrepository.com/artifact/org.junit.vintage/junit-vintage-engine
Related to changes in #299
=> Fix incorrect junit groupid

pom.xml
Upgraded bcpkix-jdk15on to 1.66
=> SEC-1474---Upgraded bcpkix-jdk15on to 1.66

pom.xml
Release notes:
- https://github.com/spotbugs/spotbugs/blob/4.2.0/CHANGELOG.md
- https://github.com/jacoco/jacoco/releases/tag/v0.8.6
=> update Spotbugs and Jacoco plugins for recent JDK support

pom.xml
Add jolokia & prometheus versions to properties
Relevant updates to `common-docker`: https://github.com/confluentinc/common-docker/pull/127
(https://confluentinc.atlassian.net/browse/ST-4106)
=> ST-4106: Uplift metrics related jars to CP Images

pom.xml
This fixes a NPE, see the following for more details:
https://github.com/jeremylong/DependencyCheck/issues/3360
https://github.com/jeremylong/DependencyCheck/issues/3361
Thanks to @dimitarndimitrov for figuring it out.
=> Update dependency-check to 6.1.6

pom.xml
cherry picks https://github.com/confluentinc/common/pull/223 back to 5.2.x
=> update spotbugs and jacoco for improved jdk support

Makefile, create_archive.sh
Support new security patch release pattern.
Add new security suffix for packaging name.
=> ST-5057: security patch release support

pom.xml
Release notes: https://github.com/spotbugs/spotbugs/blob/4.3.0/CHANGELOG.md
=> update spotbugs for recent Java version support

pom.xml
Versions 3.0.0 and later require Java 8, see https://github.com/mockito/mockito/releases/tag/v3.0.0
=> update mockito to 3.11.2

pom.xml
Release notes: https://github.com/jacoco/jacoco/releases/tag/v0.8.7
=> update jacoco to 0.8.7 for Java 16 support

pom.xml
* enables support for recent Java versions
=> update maven dependency plugin to 3.2.0

pom.xml
=> Upgrade bcprov-jdk15on to 1.68

pom.xml
=> Upgrade Zookeeper to 3.5.9.

assembly-plugin-boilerplate/pom.xml
Reverts confluentinc/common#389
=> Revert "Add license to assembly-plugin-boilerplate"

pom.xml
This probably flows through pint merge.
=> Remove redundant Netty Version definition.

pom.xml
=> Upgrade Netty

pom.xml
Release notes: https://github.com/spotbugs/spotbugs/releases/tag/4.5.3
=> chore: update spotbugs to 4.5.3

pom.xml
* improved support for Java 9+, see release notes
https://github.com/rhuss/jolokia/releases/tag/v1.7.1
https://github.com/rhuss/jolokia/releases/tag/v1.7.0
=> chore: update jolokia agent

pom.xml
* upgrade checkstyle for Java 17 support
release notes: https://checkstyle.sourceforge.io/releasenotes.html#Release_9.3
=> chore: update checktyle version

pom.xml
fixes issues with recent Java versions
=> chore: update mockito to 4.5.1

pom.xml
mostly bugfixes, see release notes:
https://github.com/mockito/mockito/releases/tag/v4.6.1
https://github.com/mockito/mockito/releases/tag/v4.6.0
=> chore: update mockito to 4.6.1

pom.xml
fix a false positive
https://github.com/spotbugs/spotbugs/issues/2040
=> chore: bump spotbug to 4.7.1

pom.xml
https://confluentinc.atlassian.net/browse/APPSEC-1412
=> APPSEC-1412: Upgrade JUNIT in 5.4.x only

pom.xml
https://nvd.nist.gov/vuln/detail/CVE-2022-24823
=> Upgrade Netty to 4.1.79.Final

pom.xml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
=> Merge Conflict Resolution (from 7.4.x to master)

pom.xml
Context: [AUDIT-1600](https://confluentinc.atlassian.net/browse/AUDIT-1600), [CC-19476](https://confluentinc.atlassian.net/browse/CC-19476) and [CC-18288](https://confluentinc.atlassian.net/browse/CC-18288).
Here is a reference to a past similar [PR-505](https://github.com/confluentinc/common/pull/505) where logredactor version was updated.
[AUDIT-1600]: https://confluentinc.atlassian.net/browse/AUDIT-1600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CC-19476]: https://confluentinc.atlassian.net/browse/CC-19476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CC-18288]: https://confluentinc.atlassian.net/browse/CC-18288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
=> AUDIT-1600: Updating logredactor version to 1.0.12.

log4j-extensions/pom.xml, pom.xml
Reverts confluentinc/common#528
=> Revert "add log redactor dependency"

pom.xml
release notes https://github.com/easymock/easymock/releases/tag/easymock-5.2.0
add support for java 17
=> update easymock support for java 17 support

pom.xml
Update reload4j for security hygiene customer reported  sonatype-2023-2736 sonatype-2022-5401 
Fix spelling of "specification"
=> update reload4j, fix typo

pom.xml
This reverts commit 9862a1ce73064e8e4ce60a371f2c141aabdcbaff.
=> Revert "disable retirejs"

pom.xml
Update bouncycastle provider and algorithm API to match the versions used in ce-kafka.
=> APPSEC-3390: update bouncycastle

pom.xml
added a new docker-arm profile to build docker containers in arm64
(cherry picked from commit 911b5699ec1475efde0df2d3ab05994db759d02d)
=> Adding PR #563 - docker-arm profile to build docker containers

pom.xml
Update jose4j to address CVE-2023-51775
=> APPSEC-3833: Update jose4j 

pom.xml
Update
Netty from 4.1.00.Final to 4.1.108.Final to address CVE-2024-29025 in netty-codec
=> update netty to 4.1.108.Final

pom.xml
Updating dependency based on this ticket by Jira bot https://confluentinc.atlassian.net/browse/DGS-10520. Will be pint merged to master
=> DGS-10520: Update netty to 4.1.108-Final

pom.xml
Update bouncycastle to address: CVE-2024-30172 CVE-2024-30171 CVE-2024-29857
=> update bouncycastle to address CVEs

pom.xml
Update bouncycastle dependencies to the latest, fips certified version
=> [APPSEC-4530 APPSEC-4536]Update bouncycastle version2

pom.xml
update bouncycastle to version 2.0
=> [APPSEC-4536][APPSEC-1226]update bouncycastle to version 2.0 (#11)

pom.xml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
=> Merge Conflict Resolution (from 7.1.x to 7.2.x)

pom.xml
update avro version to 1.11.4 to patch potential attack vector described in https://issues.apache.org/jira/browse/AVRO-3985
=> Update avro to 1.11.4

pom.xml
Update Avro to 1.11.4 to patch AVRO-3985 : https://issues.apache.org/jira/browse/AVRO-3985
=> Upgrade avro to 1.11.4

pom.xml
Bump avro version to 1.11.4 to 7.8.0
=> Bump avro version to 1.11.4 - 7.8.0

pom.xml
Update versions of avro and jetty
=> [APPSEC-4750] update avro and jetty

pom.xml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
=> Merge Conflict Resolution (from 7.7.x to 7.8.x)

pom.xml
=> rename okio -> okio-jvm

pom.xml
Merging together #707 and #721
=> update java to version 17 and avro to 1.120

.semaphore/semaphore.yml
we already upgraded here:
https://github.com/confluentinc/common/commit/34f3ad497b12b0316e24116a275f3aca56bb23bc
=> upgrade sem java version to 17 as we already upgraded to 17 here.

pom.xml
Add commons-codec definition to unify versions with ce-kafka.
=> add commons codec to dependency management

pom.xml
=> [APPSEC-5012] update mina-core

pom.xml
Update to the latest version of jetty in 9 major branch
=> [APPSEC-4836]update jetty to 9.4.57

pom.xml
update bouncycastle to major version 2. This is hopefully the end of saga #708 #646
=> [APPSEC-4526] update bouncycastle dependencies

pom.xml
update Netty to the latest available version
=> update netty to 4.1.118

pom.xml
Update JMX_exporter to address performance issues reported by a customer.
=> [FF-20502 ]update jmx_exporter

pom.xml
=> update logredactor for the log4j2 migration

pom.xml
bump spotbug to resolve kafka-schema-registry-parent error
=> [CPTF-1015]upgrade spotbugs version

pom.xml
Update protobuf version to match kafka protobuf upgrade.
=> Update Probuf version to match kafka

.semaphore/semaphore.yml
=> Update node config for semaphore

pom.xml
Pin commons libraries beanutils and validator to address known vulnerability and unify version with ones used in ce-kafka.
=> pin commons beanutils and validator

pom.xml
=> APPSEC-5859: update azure libraries

pom.xml
Provide updated commons-lang3 and grpc versions and dependency management
=> Add dependency management for grpc libraries and commons-lang3
