confluentinc/common

package/pom.xml

fixes usage of Maven in another working directory
The following assumes you are in parent directory
Before:
```
$ mvn -DskipTests -f common package
...
[INFO] package ............................................ FAILURE [  0.259 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.068 s
[INFO] Finished at: 2016-08-31T18:22:28-05:00
[INFO] Final Memory: 15M/360M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.2:single (package-assembly) on project common-package: Error reading assemblies: Error locating assembly descriptor: …
```

use basepath in maven-assembly-plugin config

---

config/src/main/java/io/confluent/common/config/ConfigUtils.java
config/src/test/java/io/confluent/common/config/ConfigUtilsTest.java

The java.util.Properties class was intended to store only String values.  However, because of a design mistake, it can actually store arbitrary Objects.  They are not returned when Properties#getProperty is invoked, but they are returned when Properties#get is invoked.
Formerly, these values would cause a bug in ConfigUtils#translateDeprecated, because they would appear in the key enumeration, but getProperties would return null for them.  This bug is fixed by calling get() instead of getProperty().

CPKAFKA-437: Make ConfigUtils#translateDeprecated robust against non-string Properties values

---

pom.xml

Use junit categories to separate unit from integration tests. Configured executions of the sure-fire plugin.

different executions of unit and integration tests

---

metrics/pom.xml
package/pom.xml
parent/pom.xml
pom.xml
utils/pom.xml

this does a couple things
1. renames current common parent/module pom to `common-parent`
2. creates a replacement parent with the old name for downstream deps to use (this is the `parent` module)
3. re-add the integration test configs to `common-parent`

Integration test pom fixins

---

pom.xml

using project.version forces downstream poms to follow
cp versioning. *some* people don't want to do this :)

CP-458: separate cp dep versions for libs

---

build-tools/src/main/resources/checkstyle/checkstyle.xml

As discussed in the `#code-quality` slack channel, this check does more harm than good.
I think this removes the ClassFanOutComplexity check.

Remove ClassFanOutComplexity check

---

build-tools/src/main/resources/checkstyle/checkstyle.xml

Do-while loops are handled poorly by the `RightCurly` module when using Checkstyle 6.19; the behavior is corrected in version 7.0+, but we can't switch to that right now as it requires JDK 8+. As a result, this fix can be added in the meantime to avoid false negatives on correctly-formatted do-while loops. As a further plus, it should also allow suppressions like [this](https://github.com/confluentinc/blueway/blob/15b4632e1b4321cf6cb9938f54af388a882eab36/checkstyle/suppressions.xml#L122-L126) to be removed.

Add fix for do-while loops with checkstyle

---

pom.xml

This allows one to use Java 9 and compile for older releases safely. See: http://openjdk.java.net/jeps/247
`mvn compile` and `mvn test` succeed when running with Java 9, but I saw some exceptions when running `mvn` with debug enabled. We'll probably have to bump the version of a number of plugins for everything to work correctly with Java 9. We can do that in a separate PR though.

Use --release instead of --source/--target if compiling with Java 9

---

pom.xml

Moving integration tests to failsafe plugin will accomplish several things:
- Shorter development iteration, since integration-test phase comes after package phase
- Unit tests will be run first before any of the integration tests
- A single failing integration test will not prevent other integration tests from running
- Separate test reports for integration and unit tests
This may impact any downstream projects that depend on shaded jars in their integration tests. If you have one of those please come talk to me.

Use maven-failsafe-plugin for integration-tests

---

package/pom.xml
pom.xml

The main motivation is Java 9 support, but also fixed the version
for some commonly used plugins that were previously dependent
on the Maven version being used.
Also fix some inconsistencies: we now use pluginManagement
backed by properties for all plugin versions.

Update maven plugin versions and powermock

---

pom.xml

Move avro version so both schema registry and storage common can use it.
Signed-off-by: Arjun Satish <arjun@confluent.io>

CC-1333: Move avro version variable from schema registry

---

pom.xml

1.8.2 contains a critical bug https://issues.apache.org/jira/browse/AVRO-2122
which customers are encountering. Although a fix is available
https://github.com/apache/avro/pull/276, it isn't merged yet and Avro releases
are very infrequent. The bug is not present in 1.8.1 and of the
fixes/improvements from 1.8.1 to 1.8.2 we are pretty confident 1.8.1 is going
to be the better release to go with.

CLIENTS-835: Downgrade Avro from 1.8.2 to 1.8.1

---

config/src/main/java/io/confluent/common/config/ConfigDef.java
config/src/test/java/io/confluent/common/config/ConfigDefTest.java

The `ConfigDef` in Kafka already has support for this; adding it to enable subclassing of `ConfigDef` while still playing nicely with our `rest-utils`, specifically the idiom of creating a `ConfigDef` by starting with the `RestConfig.baseConfigDef()` method and chaining `define()` calls from there.

MINOR: Add copy constructor for ConfigDef

---

pom.xml

Some projects that depend on common are using Avro 1.8.2
already and this causes issues in the tarball
distribution due to multiple versions in the classpath.
Thanks to @maxzheng for diagnosing a system test
failure due to this issue.

Upgrade Avro to 1.8.2

---

Jenkinsfile

kafka-trunk is a freestyle job and will not work with upstreamProjects as we append the branch after the job name.
We could fix upstreamProjects to work, but probably better without as having to maintain the branch mapping is not going to happen, which is the case based on current values used. So just drop it until we have better ways to map the branches automatically.
Also change to use dockerfile as docker_oraclejdk8 is deprecated
Replay: https://jenkins.confluent.io/job/confluentinc/job/common/job/4.1.x/151/

Add license as upstream and remove kafka

---

pom.xml

Upgrade strongly recommended due to security fixes for
jackson-databind (same as ones in 2.7.9.4 and 2.8.11.2).

Upgrade Jackson to 2.9.6

---

build-tools/src/main/resources/checkstyle/checkstyle.xml

checkstyle.redundantimport.severity property using either propertyExpansion or propertiesLocation settings

Adds opt-in rule for detecting redundant imports

---

build-tools/src/main/resources/checkstyle/checkstyle.xml

checkstyle.redundantmodifier.severity property using either propertyExpansion or propertiesLocation settings

Adds opt-in rule for detecting redundant modifiers

---

build-tools/src/main/resources/checkstyle/checkstyle.xml

checkstyle.hideutilityclassconstructor.severity property using either propertyExpansion or propertiesLocation settings

Adds opt-in rule for hiding the constructor of utility classes

---

build-tools/src/main/resources/checkstyle/checkstyle.xml

checkstyle.finalclass.severity property using either propertyExpansion or propertiesLocation settings

Adds opt-in rule for final utility classes.

---

build-tools/src/main/resources/checkstyle/checkstyle.xml

checkstyle.finallocalvariable.severity property using either propertyExpansion or propertiesLocation settings

Adds opt-in rule for final local variables.

---

build-tools/src/main/resources/checkstyle/checkstyle.xml

Downstream projects can enable the check by setting the severity higher (e.g. warning or error) with the `checkstyle.finalparameter.severity` property using either `propertyExpansion` or `propertiesLocation` settings for the checkstyle plugin (https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/custom-property-expansion.html).

Add FinalParametersCheck as an optional checkstyle check.

---

build-tools/src/main/resources/checkstyle/checkstyle.xml

[Out style guide](https://confluentinc.atlassian.net/wiki/spaces/Engineering/pages/5505079/New+Hire+Onboard#NewHireOnboard-CodingStyle) has a specific order of imports.
I'm seeing a lot of PRs with different orders of imports - making the code yo-yo back and forth and making reviews larger than they need to be.
This PR adds the `CustomImportOrder` check to ensure the import order matches our style guide.
The new check is disabled by default, (otherwise it will break downstream projects).
checkstyle.customimportorder.severity property using either propertyExpansion or propertiesLocation settings
for the checkstyle plugin. See: https://maven.apache.org/plugins/maven-checkstyle-plugin/exam …

Add opt-in rule for Imports ordering rule to match Confluent style guide

---

pom.xml

Having sl4fj-log4j12 as an explicit test-scoped dependency causes subtle
issues for downstream projects that use common-pom as a parent.
Projects that need log output during test runs, should either explicitly
declare a dependency on slf4j-log4j12 (either test or runtime scoped,
depending on whether that project should ship a logging implementation).
Bear with me, but here's an example of what can happen:
- project A uses common-parent and has sl4fj-log4j12 as a runtime dependency
- project B also uses common-parent and has project A as dependency
You would expect that project B would now also have slf4j-log4j12 as a
runtime dependency. Except, because common-parent has an explicit
depenency in test-scope, this now overrides the scope defined in A.
As a result, project B now doesn't …

slf4j-log4j12 in test scope causes downstream issues

---

build-tools/src/main/resources/checkstyle/checkstyle.xml
pom.xml

This, in general, works better with IDEs that a suppression file, and puts the suppression with the code.
E.g. to suppress a one or more rules:
```
// CHECKSTYLE_RULES.OFF:  ClassDataAbstractionCouplingCheck|CyclomaticComplexityCheck - This class is complex because blah blah blah
public class SomeJustifiablyComplexClass {
...
}
// CHECKSTYLE_RULES.ON:  ClassDataAbstractionCouplingCheck|CyclomaticComplexityCheck
```
E.g. to turn of checkstyle all together:
```
// CHECKSTYLE:OFF - Checkstyle is turned off because this code is generated by blah.
... some generated code.
// CHECKSTYLE:ON
```

Add ability to suppress checkstyle rules using comments.

---

build-tools/src/main/resources/checkstyle/checkstyle.xml

Original ImportOrderCheck added was based of Ewen's intelliJ code style file, which was meant to be GoogleStyle, but had some differences.  This PR sets the import order to true Google Style.
Should be OK to change as this was recently added, by me, so I doubt anyone is using this yet.

Correct import order from 'EwenStyle' to 'GoogleStyle'

---

pom.xml

The correct artifact is `org.powermock:powermock-api-mockito2` for version `2.0.0-beta.5`. See the [Maven Central listing](https://search.maven.org/#search%7Cga%7C1%7Cpowermock-api-mockito).

MINOR: Corrected version of Powermock Mockito artifact

---

pom.xml

We recently pinned the version of the `maven-plugin-info-reports` plugin to 3.7.1, and this resulted in some new warnings about blacklisting repositories. For example:
```
[WARNING] The repository url 'https://nexus.confluent.io/repository/maven-public' is invalid - Repository 'confluent-nexus-central' will be blacklisted.
```
Apparently disabling the dependency locations check will eliminate these warnings.

MINOR: Disabled dependency location feature of maven-plugin-info-reports

---

pom.xml

Newer versions break when processing Kafka code. A couple of examples:
```text
Error processing opcode checkcast @ 63 in kafka.security.auth.SimpleAclAuthorizer.logMessage$1 : (Lorg.apache.kafka.common.security.auth.KafkaPrincipal;ZLkafka.security.auth.Operation;Lkafka.security.auth.Resource;Ljava.lang.String;)Ljava.lang.String;
```
```text
Error processing opcode checkcast @ 31 in kafka.cluster.Broker.toString : ()Ljava.lang.String;
java.lang.IllegalArgumentException: Unknown signature [Ljava/lang/Object; for number 4
At edu.umd.cs.findbugs.OpcodeStack$Item.<init>(OpcodeStack.java:671)```

Revert to SpotBugs 3.1.5

---

pom.xml

- spotbugs 3.1.8 fixes the issue we saw in #169
- easymock 4.0.1 for JDK11 support
- powermock 2.0.0-rc3 for JDK11 support

Upgrade spotbugs, easymock, powermock

---

config/src/main/java/io/confluent/common/config/AbstractConfig.java
config/src/main/java/io/confluent/common/config/ConfigDef.java
config/src/main/java/io/confluent/common/config/ConfigException.java
config/src/main/java/io/confluent/common/config/ConfigUtils.java
config/src/main/java/io/confluent/common/config/types/Password.java

starting the process of getting cp -> ak configs
once we rip it out of downstream deps we can remove this code

deprecate common configs

---

pom.xml

Not skipping these can result in errors in CI due to resolution issues (in particular for the system scope):
```
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:3.3.4:check (default) on project kafka-connect-hdfs: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR] 	Unable to resolve system scoped dependency: jdk.tools:jdk.tools:jar:1.8:system
```
Scanning these scopes isn't worthwhile anyway because system and provided scopes aren't under control of the project being built (in fact a different version may be provided by the user) and we don't actually ship the test scope so vulnerabilities in the test scope aren't generally relevant.

Skip system, provided, and test scopes in dependency-check

---

pom.xml

Need to update the powermock.version for unit test patch usage here: https://github.com/confluentinc/blueway/pull/1820/files#r268935692 (the unit test in this PR needs to mock private field as license manager in 5.1.x, which requires latest version of powermock.version: 2.0.0)
Completed the tests by just running `$mvn surefire:test` in the `build.sh` in muckrake and they all passed.

Updated powermock.version for unit test patch usage

---

pom.xml

This version includes the following fixes from their changelog:
> 1.4.9 (released October 25 2018)
> - Upgrade docker-client dep from 8.14.2 to 8.14.3 to fix spotify/docker-client#1100
> 
> 1.4.8 (released October 23 2018)
> - Upgrade docker-client dep from 8.14.0 to 8.14.2
> - Upgrade com.sparkjava:spark-core to fix CVE-2018-9159
> - Improve documentation on referencing build artifacts
> 
Some of these fixes allow legal docker configs to build correctly,
which the current version throws errors on.

Upgrade to dockerfile-maven-plugin with bugfixes

---

pom.xml

This patch adds the buildnumber plugin to the common parent pom, and
uses it to add the commit sha to jars. The buildnumber plugin populates
the attribute ${buildNumber} with the git sha, which is then picked up
by the maven archiver and added to the jar manifest.
Build number plugin wiki:
https://www.mojohaus.org/buildnumber-maven-plugin/
Usage:
https://www.mojohaus.org/buildnumber-maven-plugin/usage.html

Add the buildnumber plugin and use it to add the commit sha to jars

---

pom.xml

Some more details are in ST-1837 , but this is to unblock some failures in operator tests and for operator customers as a result of inconsistency between the version here (1.7.25) and the version used with kafka (1.7.26). We will be fixing in 5.3 at this stage due to the operator requirements and the confidence since this has been running with kafka for some time.
Signed-off-by: sdanduConf <sdandu@confluent.io>

update slf4j version from 1.7.25 to 1.7.26 to fix ST-1837

---

pom.xml

The `create-licenses-for-docker` task should use `${licenses.version}` to match the corresponding dependency.
The `make-assembly-for-docker` task should use `${confluent.version}` to match the corresponding dependency.
This is needed for projects which inherit from this POM but set a different `project.version`.  This was the original intent of 3eec8d831e9b3ae0ac25563a1162afdae4e0b5bf but has regressed for the `docker` profile.
See [this build](https://confluentinc.semaphoreci.com/jobs/eeea0cfc-c8de-45ea-9da0-65b6f745fe38#L177) for an example.

Fix version references for licenses and assembly tasks

---

pom.xml

Some downstream components are hitting the following regression in 2.9.9.2
https://github.com/FasterXML/jackson-databind/issues/2395

MINOR: upgrade jackson-databind to 2.9.9.3

---

pom.xml

this property will be used by some of the new docker image builds so i am putting it in the common pom docker step so it doesn't have to be defined in several pom files with in the docker repos.

ST-2035: Adding the scala version as a property to docker builds

---

pom.xml

Fixes an issue with CP 5.4 not able to start ZK due to https://issues.apache.org/jira/browse/ZOOKEEPER-3056

Bump Zookeeper to 3.5.6 version

---

pom.xml

- jacoco now supports jdk13
- spotbugs has improved jdk11 support (includes https://github.com/spotbugs/spotbugs/pull/785)

update spotbugs and jacoco for improved jdk support

---

pom.xml

- Also switch to using jacksom bom instead of individual artifacts
For 3.3.x:
Verified that 2.9.9.x jackson jars do not exist in packages built from this change. There are still some older jackson jars in the pkg that get pulled in from `kafka` and `kafka-connect-s3` but those don't use jackson from the common pom.
For 5.3.x:
Verified that 2.9.9.x jackson jars do not exist in packages built from this change except for when pulled in by `kafka`.
I haven't tested 5.4.x or master since they appear unstable at the moment, but I don't expect them to be any different.
Note: with this switch to using the jackson bom, we should no longer need to specify the jackson/jackson-databind versions in the common pom anymore. For now, I've left them in for backward compatibility in case any child poms use …

Update to jackson 2.9.10

---

build-tools/src/main/resources/checkstyle/checkstyle.xml

Currently, custom exception classes count towards a classes CDAC count.  This encourages people to use more generic/general exception classes, rather than ones that are more targeted / expressive.
This PR excluded exception classes by default from the CDAC count check, and also makes the set of excluded classes configurable per-project.

exclude exception classes from ClassDataAbstractionCoupling count

---

build-tools/src/main/resources/checkstyle/checkstyle.xml

This allows the `@SuppressWarnings` annotation to be used to suppress checkstyle violations.
This is more structured than the `// CHECKSTYLE:OFF` comments in that the annotation naturally scopes the suppression to an element in the AST (class, method, statement) without needing a corresponding `// CHECKSTYLE:ON`.
https://checkstyle.sourceforge.io/config_filters.html#SuppressWarningsFilter

Add SuppressWarningsFilter to checkstyle config

---

pom.xml

Adding a config property to the maven docker plugin so that we can override the name of the Dockerfile to use when building images. This is required so that we can build rhel and debian images. I had to upgrade the docker maven plugin in order to get this feature.

ST-2560: Adding support for building debian and rhel docker images

---

pom.xml

xml feed is removed form 2020, https://nvd.nist.gov/vuln/data-feeds. We should switch to json feed.

update cve to json feed

---

pom.xml

In a few special cases we may want to allow a build to pass even with
CVEs, in particular to not block publishing SNAPSHOTs during
development.

Add flag to allow disabling dependency-check

---

pom.xml

I don't think we need net assembly since we are purely java code base? This often give some false positive report in logs, like 
```
[2020-02-02T01:20:02.052Z] [ERROR] ----------------------------------------------------
[2020-02-02T01:20:02.052Z] [ERROR] .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'dotnet' executable could not be found on the path; either disable the Assembly Analyzer or configure the path dotnet core.
[2020-02-02T01:20:02.052Z] [ERROR] ----------------------------------------------------
```
The oss index contains some vulnerability NVD may not have, but the oss index database connection is unreliable and often cause the build to fail and make the build flaky. like
```
[ERROR] Failed to request component-reports
```
I …

Disable net assembly & oss index report

---

pom.xml

Verified that packaging contains 2.9.10.2.
Ref: https://github.com/FasterXML/jackson-bom/blob/d71def80b548af6fb87bcc965eedecb706917a44/pom.xml

Update to jackson databind 2.9.10.2

---

pom.xml

The current Guava version in the POM fails the dependency check stage. This new version does not.
The change here should not have any adverse consequences for repose that utilize this property since any that do should already be failing to build.
We should hold off on merging this until we're out of the blocker phase for 5.4.

MINOR: Bump Guava version to pass dependency check

---

pom.xml

Avro 1.9.2 is a bug fix release, it allows us to use the latest Jackson

Upgrade Avro to 1.9.2, Jackson to 2.10.2

---

pom.xml

junit 4.13 went on GA on January 1, 2020
Adds support for `assertThrows` and other features

Upgrade to junit 4.13

---

pom.xml

Setting this to true is the equivalent of using the --pull option when using the docker build CLI. This will make it so we don't use a locally cached version of any base images and always pull down the latest version. This is required so that when we build cp-base-new we go out and get the latest version of the OS base image we use, such as the ubi8 image.

ST-3227: Pull down the latest base image version when building docker  images with the maven plugin

---

pom.xml

Turns out we need to set this to true when building our base images, but for our images we build from other cp images created in the same job will fail with this option enabled. I am setting the default to false because that is what it used to be, and it was working correctly for all of our images except for our base image. In a separate commit I will change our base images to set this to true.

ST-3255: Parameterize the option in docker plugin to always pull latest base image

---

pom.xml

- dependency-check>=4.0.0 will not run with JDK7. So we conditionalize
the check in a profile thats only activated if JDK>=1.8
Original issue:
```
aegelhofer@Andrew-Egelhofer's- common % export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/
aegelhofer@Andrew-Egelhofer's- common % export JAVA_TOOL_OPTIONS="-Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -Dhttps.cipherSuites=TLS_RSA_WITH_AES_128_CBC_SHA256"
aegelhofer@Andrew-Egelhofer's- common % mvn -version
Picked up JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -Dhttps.cipherSuites=TLS_RSA_WITH_AES_128_CBC_SHA256
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3/libexec
Java version: 1.7.0_80, vendor: Oracle Corporation, runtime: …
```

ST-3339: Make dependency-check execution a JDK8 activated profile

---

pom.xml

This aligns with Kafka and should fix some issues we've seen in muckrake for tests
that use MiniKdc.

Update Scala version to 2.13

---

pom.xml

It fixes 30 issues, including third party CVE fixes, several leader-election related fixes and a
compatibility issue with applications built against earlier 3.5 client libraries (by restoring a few
non public APIs).
See ZooKeeper 3.5.8 Release Notes for details: https://zookeeper.apache.org/doc/r3.5.8/releasenotes.html

Update ZooKeeper to 3.5.8

---

pom.xml

This PR pins any downstream projects that use this pom as a parent, to an absolute version of Scala (including minor version).
Without this, downstream projects can bring in multiple minor versions of Scala from different dependencies, which can result in undefined behaviour.
Related PR: https://github.com/confluentinc/ksql/pull/5381

fix: Pin the Scala version

---

LICENSE-Apache
pom.xml

This enables source jars via profiles that are activated if Apache or
Confluent license files are found. This immediately works for this
repository by including the Apache license file, but downstream
repositories using this pom as a parent need to explicitly opt-in by
having these license files, ensuring only appropriately licensed code
has source jars published.

ST-1323: Enable source jars if Apache or Confluent license files are found

---

pom.xml

- many plugins now require maven 3.x
- many bugfixes and improvement for recent JDK versions
- major version upgrades:
* checkstyle plugin 3.1.1
* surefire plugin 3.0.0-M4
* spotbugs plugin 4.0.0 (spotbugs 4.0.2)
* deploy plugin 3.0.0-M1
* intall plugin 3.0.0-M1
- remove deprecated checkstyle configs
did spot-checks on a few downstream repos and didn't see issues, in no way exhaustive though.

update various maven plugins

---

pom.xml

also downgrades intall plugin to 2.5.2 since 3.0.0-M1 of install
plugin requires 3.0.0-M1 of deploy plugin according to releaes notes
https://blogs.apache.org/maven/entry/apache-maven-install-plugin-version
This is required becauses some components in our build environment are
still relying on deploy plugin 2.7.x, which prevents us from switching
to the new 3.0.x syntax for alt*DeploymentRepository which requires
removing the 'layout' component of the repo.
see https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html

downgrade maven-deploy-plugin to 2.8.2

---

log4j-extensions/pom.xml
pom.xml

- Confluent repackaged version fixes CVE-2019-17571
- all downstream dependencies that use `slf4j-log4j12` must explicitly include the following
```
<dependency>
<groupId>io.confluent</groupId>
<artifactId>confluent-log4j</artifactId>
<version>${confluent-log4j.version}</version>
</dependency>
```
There is a cyclic dependency in PR build success. This PR will not show a green build unless the downstream dependencies are all building fine. Those downstream dependencies will not build green unless they can get `${confluent-log4j.version}` definition from the updated `common/pom.xml`.

SEC-1034: log4j migration to confluent repackaged version

---

pom.xml

Upgrade gson from 2.8.5 -> 2.8.6.
Align with other repos using Gson.

METRICS-1918: bump gson from 2.8.5 -> 2.8.6

---

pom.xml

For jackson version 2.10.2, `jackson-dataformat-yaml` brings in snakeyaml v1.24, which is supposedly affected by CVE-2017-18640

ST-3988: Update jackson version to 2.10.4

---

pom.xml

It bumps jackson databind version to 2.9.10.5 which fixes about 16 critical CVEs as compared to the current 2.9.10.2
Details here: https://mvnrepository.com/artifact/com.fasterxml.jackson/jackson-bom/2.9.10.20200621
Once approved, this same update can be applied all the way back to 3.3.x using `git cherry-pick`.
5.4.x onward are on jackson version 2.10.5. So a pull request against oldest and pint merge all the way to `master` probably wouldn't have worked anyways.

SEC-1305: update jackson-bom version

---

pom.xml

This pull request updates `confluent-log4j` from `1.2.17-cp1` to `1.2.17-cp2`. The former had a few accidental commits that made the repackaged version slightly different than the upstream `log4j`. `1.2.17-cp2` fixes the issue and applies a CVE fix (and no additional code changes) to the upstream `log4j:1.2.17`.

SEC-1334: update confluent-log4j version

---

.gitignore
Jenkinsfile
ci.py
logging/pom.xml
pom.xml

For the first phase of the nano versioning roll out we are only going to implement nano versioning for kafka and ce-kafka. I am updating the common repo to use version ranges for those two repos and adding the custom maven resolver plugin so that we can resolve those custom version ranges.

ST-3458: Nano versioning for kafka and ce-kafka

---

Jenkinsfile
pom.xml

This brings back the original process that we will use in the second phase of the roll out where the CI builds do not use the custom resolver, install, and deploy steps. We will now need to run the ci.py script to update the pom file with the resolved kafka versions. The way it was did not work and the deployed pom file was not correct so we need to use this process that is a little more hacky in the first phase of the roll out. I will need to update the ci-tools script so that during the first phase of the roll out it runs the ci.py script but doesn't do the other updates for the common repo. I will have another PR explaining that.

ST-3461: Nano versioning: do not run custom resolver plugin in ci builds

---

ci.py

I need to run the ci.py script from the packaging build so that we can resolve the kafka version range properties. I am adding a main entry here that will take in the required arguments and execute the run_update method. I tested it locally to make sure it works.

ST-3461: Add a main function to ci script so it can be run from packaging build

---

ci.py

When we run the ci.py script from packaging build_artifacts it will fail because it can't find the maven resolver plugin. That is because during those build_artifact builds we pass in a custom settings file to point at a different repo, and in that repo we do have the resolver plugin. So we need a way to pass in these args to this script so that when it calls maven it also uses that other repo. The script will now check for a maven environment variable with additional args and add them to the command it uses to run the resolver plugin.
I will have another PR to update the packaging script to export this environment variable with the additional settings.
I tested this locally by running the script and exporting an environment variable to make sure it added it correctly to the maven …

ST-3461: Add option to provide additional maven settings to the maven command in the ci script

---

ci.py
pom.xml

Upgrading to the latest version of our custom maven resolver plugin. This fixes an issue where it creates the installed pom even when run from the command line.

ST-3461: Upgrade the maven resolver plugin version

---

ci.py
pom.xml

The latest version of the custom maven resolver plugin requires you to specify the name of the new pom file you want to create otherwise it does not create one by default. The common pom build should be creating the installed pom file like it was before the change to the plugin so this will do that. Tested locally to make sure the file was created.

ST-3461: Specify the new pom file name when running the resolver plugin

---

debian/Makefile

Do not run the custom plugins such as the resolver plugin during this build because we already resolved the kafka version ranges. I did not enable the jenkins profile which would skip these plugins because that would also change other behavior, so I am passing in these properties that cause the three plugins to get skipped. This is backwards compatible with older releases since nothing will be affected since these properties didn't exist prior to 6.1.0. 
I also changed the maven command to run in batch mode so we don't get all the progress logging when downloading artifacts.
I tested this by running a packaging PR build using this branch.

ST-3461: Nano version: skip custom plugins during packaging build for debian

---

Makefile

Do not run the custom plugins such as the resolver plugin during this build because we already resolved the kafka version ranges. I did not enable the jenkins profile which would skip these plugins because that would also change other behavior, so I am passing in these properties that cause the three plugins to get skipped. This is backwards compatible with older releases since nothing will be affected since these properties didn't exist prior to 6.1.0.
I also changed the maven command to run in batch mode so we don't get all the progress logging when downloading artifacts.
I tested this by running a packaging PR build using this branch.

ST-3461: Nano version: skip custom plugins during packaging build for archive build.

---

Makefile

Do not run the custom plugins such as the resolver plugin during this build because we already resolved the kafka version ranges. I did not enable the jenkins profile which would skip these plugins because that would also change other behavior, so I am passing in these properties that cause the three plugins to get skipped. This is backwards compatible with older releases since nothing will be affected since these properties didn't exist prior to 6.1.0.
I also changed the maven command to run in batch mode so we don't get all the progress logging when downloading artifacts.
I tested this by running a packaging PR build using this branch.

ST-3461: Nano version: skip custom plugins during packaging build for rpm.

---

log4j-extensions/pom.xml
pom.xml

This pull request cherry-picks two commits from `master` and applies that to the older branch.
The first commit replaces upstream `log4j:log4j:1.2.17` with `io.confluent:confluent-log4j:1.2.17-cp1`.
The second commit updates `1.2.17-cp1` to `1.2.17-cp2`

SEC-1307: Backport "log4j replacement with confluent repackaged version"

---

ci.py
pom.xml

Problem:
Open source contributors could not build the common repo because it would fail to resolve the version range for ce-kafka because they don't have access to those artifacts.
Solution:
The new version of the maven resolver plugin has an option for not failing when it can't resolve one of the kafka version ranges. I set it to always fail if it can't resolve the ccs kafka version range because people should always have access to those artifacts. For the ce-kafka version range it will not fail when running locally if it can not resolve that version range, but will fail during CI builds if it can not find ce-kafka artifacts.
When testing this locally I made sure it works when not connected to our internal artifactory instances which mimics the behavior of some one from open source …

Update maven resolver plugin. Do not fail if ce-kafka version is not resolved.

---

pom.xml

Kafka upstream in trunk started using Junit5 [1], which refactored a lot of its components into different artifacts now. This is change adds the `org.junit.jupiter` artifacts here. Projects impacted so far:
* `common-docker` https://github.com/confluentinc/common-docker/pull/111
* `kafka-streams-examples` https://jenkins.confluent.io/job/confluentinc/job/kafka-streams-examples/job/master/2297/
[1] https://github.com/apache/kafka/pull/9231

Add org.junit.jupiter testing dependencies

---

.gitignore
Jenkinsfile
assembly-plugin-boilerplate/pom.xml
build-tools/pom.xml
config/pom.xml
log4j-extensions/pom.xml
log4j2-extensions/pom.xml
logging/pom.xml
metrics/pom.xml
package/pom.xml
parent/pom.xml
pom.xml
utils/pom.xml

Setting the jenkins config to use nano versioning. No longer need to define upstream repos as we now define downstream repos which will be automated in the future. Removed all of the snapshot versions and replaced with nano versions. Updated all of the dependency versions.
I have removed confluent.version as we should no longer be using a single version to reference dependencies, but instead use the version property associated with each repo. I also replaced the license.version property with io.confluent.license-file-generator.version
These changes will be merged during phase two of the nano versioning roll out.

ST-3461: Implement nano versioning

---

Makefile

Updated the regex used to get the rpm version so it supports the format of nano versioned releases.
These changes will be merged during phase two of the nano versioning roll out.

ST-3461: nano versioning

---

pom.xml

The version 1.60 of bcpkix-jdk15on caused a list of vulnerabilities. We need upgrade it to 1.66.

SEC-1474---Upgraded bcpkix-jdk15on to 1.66

---

pom.xml

This pull request updates jackson-databind to 2.10.5.1, which fixes CVE-2020-25649. Jackson-bom transition from 2.10.5 => 2.10.5.20201202 only updates jackson-databind, and doesn't affect other jackson jars. See [here](https://mvnrepository.com/artifact/com.fasterxml.jackson/jackson-bom/2.10.5.20201202).
Ideally, this should be applied to all the branches from 5.4.x to master. I don't expect any merge issues, since all branches are currently on the same version.

MINOR: Update jackson databind to 2.10.5.1

---

pom.xml

Affected versions are 1.65 and 1.66
Fixed in 1.67 and 1.68, went ahead with 1.68
https://nvd.nist.gov/vuln/detail/CVE-2020-28052
This also exists only as test dep in AK, so we will merge into CP first

SEC-1789 Bump bouncycastle

---

pom.xml

See the last comment in https://confluentinc.atlassian.net/browse/MMA-9930
This Guava definition is already in 5.2.x and newer. 
This change will be applied to 5.0.x and 5.1.x only.

MMA-9930: Sync Google Guava version.

---

assembly-plugin-boilerplate/pom.xml
build-tools/pom.xml
pom.xml

You know those ERRORS that dont' seem to cause build failures about "Unknown packaging: bundle"? These ones:
```
[WARNING] Unable to create Maven project for com.fasterxml.jackson.module:jackson-module-scala_2.10:jar:2.10.5 from repository.
[2021-02-26T17:33:11.320Z] org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[2021-02-26T17:33:11.320Z] [ERROR] Unknown packaging: bundle @ line 6, column 16
[2021-02-26T17:33:11.320Z] 
[2021-02-26T17:33:11.320Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:207)
[2021-02-26T17:33:11.320Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:342)
[2021-02-26T17:33:11.320Z]     at …
```

MINOR: Bump version of maven-project-info-reports-plugin to 3.1.1

---

pom.xml

https://github.com/confluentinc/common/issues/317
Resolver plugin causes build failures when it has fixed version `versionRange`. I fixed it in resolver 0.6.0. https://github.com/confluentinc/resolver-maven-plugin/pull/7
Update resolver plugin version to 0.6.0
Try to apply the same change on 6.1.0-post branch or 6.1.0 tag

ST-5085:Update resolver plugin

---

pom.xml

Downstream validation passed here, but more importantly, it also passed on `master` (see #327 and its related CI runs).
It's a bit too much to test the same on every branch between `5.2.x` and `master`. Because of that, I'll go with the assumption that no problems on the two opposite sides (`5.2.x` and `master`) is a good enough indication that there would be no problems on the in-between branches too.

KREST-1066 Upgrade Guava to the latest version to patch CVE-2020-8908.

---

pom.xml

Exclude version of netty used by zk and use a version that has the CVE fixed.

ST-5293: Override version of netty used by ZK to address CVE

---

pom.xml

The way I had excluded the netty dependencies from zookeeper before resulted in getting a mix of versions that caused incompatibility issues between netty libraries when they were used in other modules. This change makes it so that all of the direct dependencies zookeeper has on netty are excluded and then explicitly loaded. 
This doesn't fix all of the downstream issues with rest-utils though, but it does fix some of the test issues. That is because rest-utils is not getting netty through zookeeper but from another dependency which includes other netty libraries so still get a mix. I have another PR for rest-utils to address this. I did run rest-utils and the tests with this change and those other changes and they passed several times.
I ran the dependency tree from common-docker utility …

ST-5293: Explicit load of netty dependencies

---

pom.xml

This will upgrade jackson-databind to `2.9.10.8` which will fix CVEs below 
```
com.fasterxml.jackson.core_jackson-databind 2.9.10.5  -- Upgrade options: 2.10.5.1 (CVEs Fixed), 2.10.5.1 (Recommended), 2.12.3 (Optimal)
       [cvss: 8.10 ] CVE-2020-24750 ['fixed in 2.9.10.6']
       [cvss: 8.10 ] CVE-2021-20190 ['fixed in 2.9.10.7']
       [cvss: 8.10 ] CVE-2020-35728 ['fixed in 2.9.10.8']
       [cvss: 8.10 ] CVE-2020-36189 ['fixed in 2.9.10.8']
       [cvss: 8.10 ] CVE-2020-36188 ['fixed in 2.9.10.8']
       [cvss: 8.10 ] CVE-2020-36179 ['fixed in 2.9.10.8']
       [cvss: 9.80 ] CVE-2018-14718 ['fixed in 2.9.7']
       [cvss: 8.10 ] CVE-2020-36181 ['fixed in 2.9.10.8']
       [cvss: 8.10 ] CVE-2020-24616 ['fixed in 2.9.10.6']
       [cvss: 7.50 ] CVE-2020-25649 ['fixed in 2.10.5.1, …
```

DGS-1551: upgrade jackson-bom to 2.9.10.20210106

---

pom.xml

This is the process for syncing versions of libraries for June security release. This probably will break downstream build. We will coordinate teams to fix them.

Fix zookeeper, jacksondatabind and jackson-cbor version

---

pom.xml

To be consistent with https://github.com/confluentinc/kafka/pull/565
5.3.x already uses 3.4.14.

Change zookeeper version to 3.4.14

---

pom.xml

This is to sync versions of common libraries from 5.2.x: https://github.com/confluentinc/common/commit/494caf87aa432337823c3ad2b25f554b0fd46112

Fix jacksondatabind and jackson-cbor version

---

pom.xml
utils/pom.xml

Netty is only required for tls support and that was only added in ZK 3.5.x

APPSEC-110: Exclude Netty in zookeeper 3.4.14

---

pom.xml

Release notes: https://github.com/easymock/easymock/releases/tag/easymock-4.3

update easymock for Java 16 support

---

pom.xml

(cherry picked from commit 0ff2e314ed04a89f731c1fe427fdcdde28edaec6)

SEC-1789 Bump bouncycastle to fix CVE-2020-28052 (#309)

---

build-tools/src/main/resources/checkstyle/checkstyle.xml
pom.xml
utils/src/main/java/io/confluent/common/Configurable.java
utils/src/main/java/io/confluent/common/utils/AbstractPerformanceTest.java
utils/src/main/java/io/confluent/common/utils/IntegrationTest.java
utils/src/main/java/io/confluent/common/utils/MockTime.java
utils/src/main/java/io/confluent/common/utils/PerformanceStats.java

* update checkstyle to support recent Java versions – release notes: https://checkstyle.sourceforge.io/releasenotes.html#Release_8.44
* LineLength must now defined under Checker
* fix license comments incorrectly using javadoc style

update checkstyle to 8.44 and fix checks

---

pom.xml

Makes the ZooKeeper version change to 3.6.3 as was applied in https://github.com/apache/kafka/pull/10918.

 KAFKA-12756: Update ZooKeeper to v3.6.3

---

build-tools/src/main/resources/checkstyle/checkstyle.xml

workaround for https://github.com/checkstyle/checkstyle/issues/7541
taken from https://github.com/checkstyle/checkstyle/blob/422be612a4dce54f204094449f3de75d248e2871/src/main/resources/google_checks.xml#L99-L104
this is to help backport checkstyle version upgrades and to reduce the impact on additional downstream repositories, thanks @dimitarndimitrov for the suggestion.

fix change in checkstyle behavior since 8.20

---

log4j-extensions/pom.xml
pom.xml

Apply https://github.com/confluentinc/common/pull/270/files to 5.2 and 5.3

log4j migration to confluent repackaged version

---

pom.xml

AK 3.0 has been upgrade to this version https://github.com/apache/kafka/pull/10778 and we want to keep it consistent in corresponding CP branches.

Upgrade Jackson to 2.12.3.

---

pom.xml

Update version of confluent-log4j to v.1.2.17-cp3. The new version of confluent-log4j adds logredactor v1.0.1 as a dependency. This will allow everything that uses confluent-log4j to also have access to log redactor. 
More details on logredactor:
- https://github.com/confluentinc/logredactor
- https://confluentinc.atlassian.net/wiki/spaces/SECENG/pages/2227276875/1-Pager+Cloud+Log4j+Redactor

[AUDIT-415] Update confluent-log4j version

---

Jenkinsfile

Capping in branches 5.2.x through 6.0.x the number of concurrent Jenkins jobs running down to just 2 (one running, all others queued) in order to reduce the impact of releases has on Jenkins (To cap the “Jenkins Build Storm” after releases are finalized and bumped to the next version every quarter). This change will save a lot of Jenkins build resources.

Capping the number of concurrent Jenkins jobs running 

---

assembly-plugin-boilerplate/pom.xml

Add license to assembly-plugin-boilerplate
This is cloned from https://github.com/confluentinc/common/pull/388 
cc @cjolivier01

Add license to assembly-plugin-boilerplate

---

pom.xml

This applies the same change in 6.2.x back to 5.4.x---6.1.x

Sync Netty Override From 6.2.x

---

assembly-plugin-boilerplate/pom.xml

Add license header in pom.xml in assembly-plugin-boilerplate
Background: As part of [Open source license scanning](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/2631631350/Running+FOSSA+for+open+source+license+scanning) initiativate, when scanning connect repos, `assembly-plugin-boilerplate` is flagged as No license found.
Hence adding the header in pom.xml

Add license header in pom.xml

---

pom.xml

Junit5 uses [Tags](https://junit.org/junit5/docs/current/user-guide/#writing-tests-tagging-and-filtering) instead of Category and we can only use string instead of the IntegrationTest class that we import from here when defining integration tests. To get around this, we add a new IntegrationTest group to filter on in the maven-surefire-plugin and maven-failsafe-plugin when splitting out the integration tests

Add Support to Split Up Integration Tests for Junit5

---

pom.xml

- Cherrypick of #400
- Needed to get downstream 7.1.x branches compiling without the vulnerable log4j2 versions. Earlier 7.0.x versions depend on confluent-log4j 1.2.17-cp2, which isn't vulnerable.

Bump confluent-log4j to 1.2.17-cp6

---

pom.xml

This new version of confluent-log4j removes several classes involved with log4j 1.x CVEs.
References: https://confluentinc.atlassian.net/browse/SEC-2896

[SEC-2896] Update confluent-log4j version to cp8

---

pom.xml

In order to fix log4j CVEs, confluent's fork of log4j was updated to version 1.2.17-cp2.2 and now needs to be included in all impacted patch releases branches. 
Once merged into 5.3.x, `pint merge` will update the version in all newer branches. (For 7.1.x and master, the confluent-log4j version will be 1.2.17-cp8, which includes the log redactor feature). 
References:
- https://confluentinc.atlassian.net/browse/SEC-2901

Update confluent-log4j version

---

pom.xml

Jira ticket: https://confluentinc.atlassian.net/browse/MMA-11603
**ce-kafka**'s protobuf versions are updated to `3.16.1` from 5.3.x+ in:
- https://github.com/confluentinc/ce-kafka/pull/5442/files
- https://github.com/confluentinc/ce-kafka/pull/5457/files
**blueway** and **metadata-service** need to update the version as well. 
Therefore, adding centralized protobuf version in **common** that matches with ce-kafka's version. Blueway will inherit this version, and same could be done in metadata-service.
Note:
1. From `7.1.x`+, protobuf version is defined **common**: https://github.com/confluentinc/blueway/blob/ddfa26e4775e22e2110a2dabfa216d5292512db0/pom.xml#L64. Will be careful not to overwrite it when pint-merging. 
2. metadata-service only uses protobuf version in master. So it could …

MMA-11603: Add centralized protobuf version from 5.3.x onwards

---

pom.xml

Update protobuf to 3.19.4 to address security advisory
See: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22569

chore: update protobuf version

---

pom.xml

* switch to junit-bom for junit jupiter
This simplifies the pom file and ensures downstream repositories don't
have to manually define additional junit dependencies, instead relying
on the bom to align all dependencies to the same version.
* chore: update junit jupiter to latest 3.8.2 version

import junit-bom to align junit dependencies, update to 3.8.2

---

pom.xml

Mockito 4.x has been released, updating to the latest 3.x series
so we can start removing deprecated APIs before moving to 4.x

chore: update mockito to last available 3.x version

---

pom.xml

* fixes multi-threaded warnings when running parallel builds
release notes: https://github.com/trustin/os-maven-plugin/releases/tag/os-maven-plugin-1.7.0

chore: update os-maven-plugin

---

pom.xml

Mockito 4.3.x added a bom, which should simplify dependency management
* import mockito bom to align mockito dependencies to the same version
* update to most recent mockito 4.3.1
Downstream fix for KSQL:
https://github.com/confluentinc/ksql/pull/8780

chore: update mockito and use bom

---

metrics/src/main/java/io/confluent/common/metrics/CompoundStat.java
metrics/src/main/java/io/confluent/common/metrics/JmxReporter.java
metrics/src/main/java/io/confluent/common/metrics/KafkaMetric.java
metrics/src/main/java/io/confluent/common/metrics/Measurable.java
metrics/src/main/java/io/confluent/common/metrics/MeasurableStat.java
metrics/src/main/java/io/confluent/common/metrics/Metric.java
metrics/src/main/java/io/confluent/common/metrics/MetricConfig.java
metrics/src/main/java/io/confluent/common/metrics/MetricName.java
metrics/src/main/java/io/confluent/common/metrics/Metrics.java
metrics/src/main/java/io/confluent/common/metrics/MetricsReporter.java
metrics/src/main/java/io/confluent/common/metrics/Quota.java
metrics/src/main/java/io/confluent/common/metrics/QuotaViolationException.java
metrics/src/main/java/io/confluent/common/metrics/Sensor.java
metrics/src/main/java/io/confluent/common/metrics/Stat.java

Deprecating usage of common-metrics in favor of the equivalent classes in
org.apache.kafka.metrics since all platform components have already migrated.

deprecate common-metrics

---

pom.xml

Logredactor v1.0.9 fixes the bug mentioned in AUDIT-971, which leads to a new version (1.2.17-cp9) for confluent-log4j(after bumping its logredactor dependency to v1.0.9)
References: https://confluentinc.atlassian.net/browse/AUDIT-971

AUDIT-971: Update confluent-log4j version for 7.1.x

---

pom.xml

Logredactor v1.0.10 fixes the bug mentioned in AUDIT-986, which leads to a new version (1.2.17-cp10) for confluent-log4j(after bumping its logredactor dependency to v1.0.10)
References: https://confluentinc.atlassian.net/browse/AUDIT-986

AUDIT-986: Update confluent-log4j version for 7.1.x

---

pom.xml

The previous version of 3.0.0-M5 is causing some CI builds with JDK11 to fail during integration tests (example: [master in SR repo](https://jenkins.confluent.io/job/Confluent%20Public%20Repo%20PR%20builder/job/schema-registry/job/PR-2251/1/)). This is a [known issue](https://github.com/openzipkin/zipkin/issues/3159) in 3.0.0-M5 and is resolved in 3.0.0-M6.

DGS-3535: Upgrade maven-surefire-plugin version to 3.0.0-M6

---

pom.xml

Any version below 2.8.9 is vulnerable, so bumping it to 2.9.0. This will also keep it in line with what's currently in master.

KSECURITY-277: Fix for CVE-2022-25647

---

pom.xml

fixes https://issues.apache.org/jira/browse/MDEP-753 which has caused
issues in downstream repos in the past when enforcing dependency
declarations.

chore: update maven dependency plugin

---

pom.xml

chore: update spotbugs to 4.7.0

---

pom.xml

Follow up to https://github.com/confluentinc/common/pull/449 which broke ksqlDB build (cf. https://github.com/confluentinc/ksql/issues/9060).
After this PR is merged, we can address 9060 to "unpin" the version to -M5 for ksqlDB and use -M7. -- I did a trial PR for ksqlDB to verify that `-M7` actually works for us: https://github.com/confluentinc/ksql/pull/9200

Upgrade surfire version to 3.0.0-M7

---

pom.xml

https://confluentinc.atlassian.net/browse/METRICS-4434
* improved support for Java 9+, see release notes
https://github.com/rhuss/jolokia/releases/tag/v1.7.1

chore: update jolokia agent (#434)

---

log4j-extensions/pom.xml
pom.xml

This is to cherry-pick changes in 7.2.x (https://github.com/confluentinc/common/pull/450 and https://github.com/confluentinc/common/pull/451) to migrate confluent-log4j to reload4j.

APPSEC-1393:Migrate from confluent-log4j to reload4j [5.4.x -- 7.0.x]

---

disk-usage-agent/pom.xml

This is needed because https://github.com/confluentinc/common/pull/464 is from 5.4.x and does not have disk-usage-agent project (This is only from 6.2.x). So this change will only be applied to 6.2.x and 7.0.x.

APPSEC-1393: Fix dependency in disk-usage-agent [6.2 and 7.0]

---

pom.xml

Start from maven 3.8.1, maven blocks external HTTP repositories by default. We should use https link for repositories
Modify `http` to `https` for repositories

chore: Use https for repositories

---

disk-usage-agent/src/main/java/io/confluent/agent/monitoring/DiskUsage.java
disk-usage-agent/src/main/java/io/confluent/agent/monitoring/Volume.java

Fixing below errors
```
30861 [2022-07-27T19:49:25.071Z] [ERROR] /home/jenkins/workspace/s_rs-start-stabilization-process/prod/common/disk-usage-agent/src/main/java/io/confluent/agent/monitoring/Volume.java:93:22: '+' s       hould be on a new line. [OperatorWrap]
30862 [2022-07-27T19:49:25.071Z] [ERROR] /home/jenkins/workspace/s_rs-start-stabilization-process/prod/common/disk-usage-agent/src/main/java/io/confluent/agent/monitoring/Volume.java:94:37: '+' s       hould be on a new line. [OperatorWrap]
30863 [2022-07-27T19:49:25.071Z] [ERROR] /home/jenkins/workspace/s_rs-start-stabilization-process/prod/common/disk-usage-agent/src/main/java/io/confluent/agent/monitoring/Volume.java:95:33: '+' s       hould be on a new line. [OperatorWrap]
30864 [2022-07-27T19:49:25.072Z] [ERROR] …
```

fix checkstyle

---

pom.xml

https://confluentinc.atlassian.net/browse/METRICS-4434
improved support for Java 9+, see release notes
https://github.com/rhuss/jolokia/releases/tag/v1.7.1

7.0.x: update jolokia version in pom.xml

---

Jenkinsfile

This PR add pinnedNanoVersions property, so that Jenkins will try to pin each version update in pom.xml instead of using version range.
e.g.
[7.3.0, 7.4.0) -> 7.3.0-99 after each build
- better reproducible builds, mater branch won't follow latest upstream dependency because of version range
- branch become more stable since it will reject broken changes
That is brought up by Ksql team initially because they want to have better reproducible builds. And with that change, version bumps will only happen when the upstream build is compatible. That means the mater branch will be more stable and reject broken upstream changes.
noted: `<io.confluent.license-file-generator.version>` still use version range because that dependency only get pulled when using `-Pdocker` profile which CI does not use …

chore: switch to pinned nanoversion strategy

---

pom.xml

Upgrade Jackson to 2.13.4 and Protobuf to 3.19.6.

APIF-2957: Upgrade Jackson and Protobuf versions.

---

pom.xml

This should fix the issues described at https://confluent.slack.com/archives/C09EP1SS3/p1673003459267459 with an error updating the dependency database.
See https://github.com/jeremylong/DependencyCheck/issues/5220 for more details.
Tested locally with `mvn verify` and commenting the final `<dependency.check.skip>true</dependency.check.skip>` so that the check would run.
After this is completed, I will run `apply-pint-merge` to ensure this change is propagated to other branches.

Bump to 7.4.4

---

pom.xml

Currently, we can not override `resolver-maven-plugin`'s default versionRange through cmd lines except changing `confluent.version.range`. However `confluent.version.range` will be used in other places to resolve versions as well.
Add a new parameter `versionRange` that can be overrode through cmd lines. So that we can change `resolver-maven-plugin`'s default versionRange without affecting `confluent.version.range`

fix: override maven version plugin's default versionrange

---

Jenkinsfile
ci.py
pom.xml

This PR revert changes in https://github.com/confluentinc/common/pull/506  and un-pin nano version to fallback to use version range. The reason is that it causes confusion in release.

fix: revert remove ci py

---

ci.py

Run on PR branch (derives from `6.1.x`):
```
$ python ./ci.py "anything goes" `pwd`
Running additional version updates for common
Resolving the version range for ccs kafka.
Getting version range for: kafka.version.
Version range for kafka.version is: [6.1.10-0-ccs, 6.1.11-0-ccs)
Resolving the version range for: [6.1.10-0-ccs, 6.1.11-0-ccs)
mvn --batch-mode -Pjenkins io.confluent:resolver-maven-plugin:0.6.0:resolve-kafka-range -DgroupId=org.apache.kafka -DartifactId=kafka-clients -DversionRange="[6.1.10-0-ccs, 6.1.11-0-ccs)" -Dskip.maven.resolver.plugin=false -DprintCCS -q
6.1.10-10-ccs
Resolved the version range to version: 6.1.10-10-ccs
Setting the property kafka.version to 6.1.10-10-ccs
mvn --batch-mode versions:set-property -DgenerateBackupPoms=false -Dproperty=kafka.version …
```

Return the original "version_range" if it isn't an actual Maven version range

---

pom.xml

Snakeyaml is a dependency that is brought in by multiple confluent libraries in scope "provided" that leads to unexpected, old versions of snakeyaml showing up across built projects that do not override the version. 
Adding the snakeyaml to DependencyManagment instructs projects using common to use this version of snakeyaml when resolving transitive dependencies and should hopefully resolve our woes with this library. 
After merging and testing, we should purge per-project pinning of this library. 
remove here:
https://github.com/confluentinc/schema-registry/blob/master/pom.xml#L160
https://github.com/confluentinc/kafka-rest/blob/master/pom.xml#L131
https://github.com/confluentinc/schroedinger/blob/master/pom.xml#L85 (just version definition) …

add snakeyaml to dependency management

---

pom.xml

An update of SnakeYaml to version 2.0 revealed incompatibility with Jackson < 2.14.2. Updating Jackson to 2.14.2 that was shown working with SnakeYaml 2.0 in https://github.com/confluentinc/cc-pipeline-service/pull/1153

APPSEC-2551: Update Jackson

---

pom.xml

Adding jetty and snappy to dependency management to match the versions used in ce-kafka and avoid maven builds imports with incorrect versions. e.g., bringing in kafka-clients of licensing with outdated jetty / snappy / jose

add dependency management to match versions in ce-kafka

---

pom.xml

This PR adds the CycloneDX SBOM generator plugin to the list of build plugins. This addition allows us to automatically generate SBOMs during the build time. The SBOMs are stored in $project/target/bom.[json/xml]

APPSEC-2855: add generation of SBOMs to maven based Java projects

---

pom.xml

Update jetty to 9.4.52.v20230823 to address: CVE-2023-40167 and CVE-2023-41900
Update netty to 4.1.94 to address: CVE-2023-34462

APPSEC-3039: Update jetty and netty

---

pom.xml

RetireJS (a plugin dependency consumed by dependency-check that we use) is causing issues with builds. Examples: 
- https://semaphore.ci.confluent.io/jobs/bae63f70-ccdb-412c-9c9c-0eabc9305626
- https://jenkins.confluent.io/job/confluentinc/job/metadata-service/job/7.5.x/411/console
```
[ERROR] 	InitializationException: Failed to initialize the RetireJS repo: `/tmp/dctemp772c4170-e777-4d8b-bb31-6af8dfbccdf2/jsrepository.json` appears to be malformed. Please delete the file or run the dependency-check purge command and re-try running dependency-check.02:49
[ERROR] 		caused by JSONException: No value for info
```
This is blocking builds and a [known issue](https://github.com/RetireJS/retire.js/issues/423), rather than waiting for a fix we can disable it for the time being by adding the ``` …
```

disable retirejs

---

pom.xml

The retire.js [issue](https://github.com/RetireJS/retire.js/issues/423) is fixed, we can re-enable that plugin. 
More context in this PR: https://github.com/confluentinc/common/pull/559
This reverts commit 9862a1ce73064e8e4ce60a371f2c141aabdcbaff.
Created this sample PR: https://github.com/confluentinc/metadata-service/pull/1960
Last week it failed with `[ERROR] Exception occurred initializing RetireJS Analyzer.`, today the [workflow](https://jenkins.confluent.io/job/confluentinc-pr/job/metadata-service/view/change-requests/job/PR-1960/) succeeded even after enabling retire.js

Revert "disable retirejs"

---

pom.xml

Upgrade to protobuf 3.24.4  .  One of the dependencies of Schema Registry requires 3.22+, we are currently on 3.19.6

Upgrade protobuf to 3.24.4

---

pom.xml

In the process of mitigating Zookeeper CVE we need to update it both in ce-kafka as well as in common so the correct version is used by maven built projects.

update zookeeper component to match version in ce-kafka

---

pom.xml

This PR removes logback logging facility removed in ce/ccs kafka as well as kafka-rest. 
This PR resolves:  CVE-2023-6378

APPSEC-xyz: exclude logback-core and logback-classic 

---

pom.xml

Excluding logback-core from zookeeper. 
This is second PR based at 6.1.x. First merge errorornously only was merged into master.

exclude logback-core and logback-classic in line with the changes in kafka

---

pom.xml

This change adds support to build docker images on `arm64` machines/laptops.
The following are the changes I have made
1. Added a new profile docker-arm that uses the [io.fabric8:docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin)
2. This plugin supports docker image building in `arm64` laptops.
_Ensuring Backward compatibility and minimum interference with existing plugin:_
1. Completely new build profile isolates the build process.
2. added additional property: `docker.imagePullPolicy` default in the common default this will not be used by existing plugin hence no interference.
3. the new plugin requires defaults for some of existing properties; added these as defaults in plugin scope so that they do not impact the existing plugin.

added a new docker-arm profile to build docker containers in arm64 

---

pom.xml

docker-arm profile should not be implicitly activated based on environment variables, otherwise it will break CI pipelines.

fix: no implicit activation of docker-arm profile

---

pom.xml

Why?
----
Bumping the `protobuf.version` 3.25.1 to match ce-kafka: https://github.com/confluentinc/ce-kafka/blob/d5268708e08e1528abee555d5a74073d7f063e81/gradle/dependencies.gradle#L206

MINOR: Bumping protobuf version to 3.25.1

---

pom.xml

This is continuation of https://github.com/confluentinc/common/pull/589 that applied the update to the master branch only

APPSEC-4033: update zookeeeper to 3.8.4

---

pom.xml

Correction of no-op #593 
Updating zookeeper to 3.8.4 in 6.2.x

APSEC-4033: update zookeper to 3.8.4

---

pom.xml

Revert jackson-databind to 2.14.2 as 2.16.2 is causing downstream build failures.
Update of jackson suite needs to be coordinated with kafka / ce-kafka

revert #595 to remediate downstream build failures

---

pom.xml

bcprov-ext-jdk18on 1.78.1 doesn't seem to be published in [mvnrepository](https://mvnrepository.com/artifact/org.bouncycastle/bcprov-ext-jdk18on). Same for [maven central](https://central.sonatype.com/artifact/org.bouncycastle/bcprov-ext-jdk18on/versions). The [release page](https://www.bouncycastle.org/latest_releases.html) seems to imply that -ext- versions should be there too.
This PR updates the bouncycastle version to 1.78 since it is a published version.
https://confluent.slack.com/archives/C05G3CNGLF9/p1714761258647209?thread_ts=1714742333.550519&cid=C05G3CNGLF9

Update bouncycastle version to 1.78

---

pom.xml

We need to synchronize versions of bouncycastle fips libraries with versions used in ce-kafka. 
The addition of the libraries to dependencyMagament section does  **not** automatically include them in the projects, just specifies which version to use if the project pulls it e.g. transitively.

add version definitions of bouncycastle fips dependencies

---

pom.xml

bouncycastle-tls-fips version added in #614 was incorrect. This remediates that issue.

add correct version of tls_fips

---

pom.xml

This PR adds azure-identity, azure-blob-storage and aws-sdk-core to dependencymanagement to use the same versions in ce-kafka and maven build projects

unify versions of aws and azure sdks with ce-kafka

---

pom.xml

This PR updated jackson libraries in common to match version in ce-kafka 7.7.x
This will likely break things as we experience before when applying to earlier version of common

update jackson to match ce-kafka

---

pom.xml

This removes the `dependency-check-maven` plugin from `pom.xml`. This plugin was once upon a time used by AppSec supposedly, but it is no longer used.

Remove dependency-check-maven plugin

---

service.yml

added so that upgrader's common-parent version stays up to date

add cc-cluster-upgrader as downstream

---

pom.xml

Upgrade of bouncycastle fips library caused incompatibility issues discovered late in testing. We need to roll back to the last certified version and match the library versions with ce-kafka.

downgrade fips library to a version that is certified compliant

---

pom.xml

Update azure identity to resolve CVE-2024-35255

APPSEC-4267: update azure-identity to 1.12.2

---

pom.xml

Pin the version of classgraph as an outdated version is brought in as a transitive dependency of mbknor-jackson.

APPSEC-4297: update classgraph

---

pom.xml

bouncycastle.version is no longer defined, consequently we should have no dependency management reffering to it

[RCCA-21560] remove dependency with missing version definition

---

service.yml

Remove cc-cluster-upgrader from downstream projects to fix the bug that caused infinite version bump loop on CI.

Remove upgrader from service.yml

---

pom.xml

The previous version 3.24 ended support 11/2023

Bump protobuf version to 3.25.4

---

.github/CODEOWNERS
pom.xml

revert the update of bouncycastle as we have no time to test this change in the 7.7.0-cp2 release. 
add appsec to codewoners to simplify the process of common repo update.

Revert bouncycastle update, udpate codeowners

---

pom.xml

Fix bouncycastle variable naming incorrectly set in the revert

[RCCA-22120] fix the variable names

---

pom.xml

proper revert of bouncycastle update

[rcca-22120] proper revert of bc update to avoid naming conflicts in downstream repos

---

.semaphore/semaphore.yml

This PR adds cp jar build task invocation for PR builds to make sure downstream components don't break with the PR changes.

CPBR-1680: adding cp-jar-build ci gating

---

pom.xml

* update bc-fips versions, add bcutil-version
* remove redundant dependencymanagement sections
* remove redudnant version definitions

[APPSEC-4536][APPSEC-1226] Update bouncycastle to 2.0 in FedRAMP branch (#10)

---

.semaphore/semaphore.yml

This PR disables cp jar build CI gating for master branch. Master branches can be unstable and can block feature development velocity.

CPBR-1780: disable CI gating workflow for master branch

---

pom.xml

Add commons-io to dependencies managed using the common repository:
- it is defined in ce-kafka
- it is used by multiple confluent repositories

define version of commons-io and add it to dependencyManagement

---

pom.xml

The late integration tests caught issues in bouncycastle 2.0 integration with ldaps. 
This is a temporary revert until q1 2025
Revert  #651 
Revert #646

[APPSEC-4526]revert bouncycastle fips libraries upgrade

---

pom.xml

Fix cp release test failures.
reference [thread](https://confluent.slack.com/archives/C027DGB2EHG/p1731389874638499?thread_ts=1729769918.268309&cid=C027DGB2EHG)

Revert bc.tls-fips version to 1.0.13

---

pom.xml

Revert the bctls-fips to even lower version 1.0.13 due to downstream failures
replaces #730 as it has to be applied to 7.1.x

[APPSEC-4526]revert bouncycastle

---

pom.xml

Update netty to resolve false positive CVE reports (vuln only affects Windows)

[APPSEC-4850] update netty to 4.1.115

---

pom.xml

Avro 1.12.0 introduces a regression caused by https://github.com/apache/avro/pull/2389

Revert upgrade to Avro 1.12.0

---

pom.xml

Pin the following to be used by downstream repos (ex: rest-utils) to support Jetty 12 migration. 
<dependency>
<groupId>jakarta.websocket</groupId>
<artifactId>jakarta.websocket-api</artifactId>
<version>2.1.0</version>
</dependency>
<dependency>
<groupId>jakarta.servlet</groupId>
<artifactId>jakarta.servlet-api</artifactId>
<version>6.0.0</version>
</dependency>
https://github.com/confluentinc/rest-utils/pull/552/files#r1999652526

Pin Jakarta versions to support Jetty 12 migration

---

pom.xml

Add `log4j-slf4j-impl` dependency to be used in downstream projects.
Ref: https://confluentinc.atlassian.net/browse/INIT-8980

Add slf4j-log4j binding dependency

---

pom.xml

Update aws SDK to match ce-kafka and support downstream applications.

udpate amazonSdkVersion to match ce-kafka

---

pom.xml

We have updated Java to version 17 per request from CPBR. Unfortunately, this is causing problems with clients expecting Java 11. 
We'll explicitly set to 17 in rest-utils, ksql, and other repos that run server-side

Use JDK 11 for client compatibilty

---

NOTICE
licenses/NOTICE.zookeeper.txt

CP 8.0 ships without Zookeeper, we should remove the notices accordingly

remove zookeeper license / notice

---

.semaphore/semaphore.yml

This PR adds a trigger for the cp-jar-build pipeline (a minimal CP packaging workflow) in the after_pipeline job. The cp-jar-build pipeline will run automatically on every commit to the master branch for upstream repositories such as ce-kafka, kafka, common and others.
Purpose:
- Proactively catch breaking changes or compilation issues introduced upstream.
- Automatically notify downstream components of failing builds.
- Continuously monitor build results and pass rates to improve stability and visibility.

CPBR-2587 Trigger cp-jar-build to verify CP packaging in after_pipeline job

---

pom.xml

Updating versions of `classgraph`, `jetty`, `jose4j`, `jacoco` and `snappy` to match ce-kafka versions in https://github.com/confluentinc/ce-kafka/pull/21588

Updating versions as per ce-kafka version upgrade in PR #21588

---

.semaphore/semaphore.yml
pom.xml

Pin versions of commons-validator and commons-beanutils to address known vulnerability.

APPSEC-5684: Update commons validator

---

pom.xml

Add dependency management for httpclient5 used in ce-kafka, 
Remove mina-core that should no longer be needed after jetty update
Remove zookeeper version and zkclient dependency management and version definitions

Cleanup in common 8.0.x: add httpclient5, remove zookeeper definitions

---

pom.xml

It appears that pint-merge has failed between 8.0.x and 8.1x for commit:
https://github.com/confluentinc/common/commit/348fe5585452c0d0f6f6cf016b1030c15fba79b0

APPSEC-5909: update jetty due to tbd, merge failure
